sudo: required

language: generic

branches:
  only:
  - master
  - /./

services:
  - docker

before_install:
  - docker build -t $DOCKER_ID/backend-api .

after_success:
  - docker build -t $DOCKER_ID/backend-api .
  - echo docker logout
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/backend-api