sudo: required

language: node_js
node_js:
  - 12

branches:
  only:
  - master
  - /./

services:
  - docker

before_install:
  - docker build -t $DOCKER_ID/backend-api .

after_success:
  - docker build -t $DOCKER_ID/backend-api .
  - echo docker logout
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/backend-api

# deploy:
#   provider: elasticbeanstalk
#   region: "ap-southeast-1"
#   app: "multi-docker"
#   env: MultiDocker-env
#   bucket_name: "elasticbeanstalk-ap-southeast-1-647466573283"
#   bucket_path: "docker-multi"
#   on:
#     branch: master
#   access_key_id: "$AWS_ACCESS_KEY"
#   secret_access_key: "$AWS_SCRET_ACCESS_KEY"
#   edge: true